//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultancy_account
    {
        public int account_id { get; set; }
        public int agent_id { get; set; }
        public int candidate_id { get; set; }
        public float amount { get; set; }
        public float due_amount { get; set; }
        public float total_amount { get; set; }
        public string del { get; set; }
    }
}
