//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultancy_medical_center
    {
        public Nullable<int> medical_center_id { get; set; }
        public string medical_center_name { get; set; }
        public System.DateTime entered_date { get; set; }
        public System.DateTime del { get; set; }
    }
}
