//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultancy_ticketing
    {
        public int ticketing_id { get; set; }
        public int candidate_id { get; set; }
        public System.DateTime arrival_date { get; set; }
        public System.DateTime departure_date { get; set; }
        public int air_lines { get; set; }
    }
}
