//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultancy_candidate
    {
        public int candidate_id { get; set; }
        public string name { get; set; }
        public string passport_no { get; set; }
        public System.DateTime passport_issued_date { get; set; }
        public System.DateTime passport_expiry_date { get; set; }
        public string issued_place { get; set; }
        public string bearer_name { get; set; }
        public string image_name { get; set; }
        public System.DateTime dob { get; set; }
        public string sex { get; set; }
        public string guardain_name { get; set; }
        public string marital_status { get; set; }
        public string religion { get; set; }
        public int agent_id { get; set; }
        public string address { get; set; }
        public string applied_country { get; set; }
        public string profession { get; set; }
        public string salary { get; set; }
        public int duty_hour { get; set; }
        public string company_name { get; set; }
        public string educational_background { get; set; }
        public System.DateTime entered_date { get; set; }
        public System.DateTime update_date { get; set; }
        public string del { get; set; }
    }
}
