//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultancy_salary
    {
        public int salary_id { get; set; }
        public int staff_id { get; set; }
        public string amount { get; set; }
        public string issued_month { get; set; }
        public System.DateTime entered_date { get; set; }
        public System.DateTime update_date { get; set; }
        public string del { get; set; }
    }
}
