//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultancy_company
    {
        public int company_id { get; set; }
        public string visa_group { get; set; }
        public int add_company_id { get; set; }
        public string id_number { get; set; }
        public string visa_number { get; set; }
        public System.DateTime date { get; set; }
        public int ccat_id { get; set; }
        public int number { get; set; }
        public System.DateTime entered_date { get; set; }
        public System.DateTime update_date { get; set; }
        public string del { get; set; }
    }
}
