//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsultancyEntities : DbContext
    {
        public ConsultancyEntities()
            : base("name=ConsultancyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<consultancy_account> consultancy_account { get; set; }
        public DbSet<consultancy_add_company> consultancy_add_company { get; set; }
        public DbSet<consultancy_agent> consultancy_agent { get; set; }
        public DbSet<consultancy_candidate> consultancy_candidate { get; set; }
        public DbSet<consultancy_candidate_category> consultancy_candidate_category { get; set; }
        public DbSet<consultancy_company> consultancy_company { get; set; }
        public DbSet<consultancy_district> consultancy_district { get; set; }
        public DbSet<consultancy_interview> consultancy_interview { get; set; }
        public DbSet<consultancy_medical> consultancy_medical { get; set; }
        public DbSet<consultancy_medical_center> consultancy_medical_center { get; set; }
        public DbSet<consultancy_medical_test> consultancy_medical_test { get; set; }
        public DbSet<consultancy_orientation> consultancy_orientation { get; set; }
        public DbSet<consultancy_salary> consultancy_salary { get; set; }
        public DbSet<consultancy_shram_test> consultancy_shram_test { get; set; }
        public DbSet<consultancy_staff> consultancy_staff { get; set; }
        public DbSet<consultancy_stamping> consultancy_stamping { get; set; }
        public DbSet<consultancy_ticketing> consultancy_ticketing { get; set; }
    }
}
