//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultancy_staff
    {
        public int staff_id { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string post { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string role { get; set; }
        public System.DateTime entered_date { get; set; }
        public System.DateTime update_date { get; set; }
        public string del { get; set; }
    }
}
